Move API timeout to constants
Put default API timeout (which cancels the request and returns a 504 if
exceeded) into constants so that it's defined in one place. (One
exception: hivemind requests, which we're okay with failing if they take
over a few seconds.)